Add compability for solc 0.8
Uniswap/v3-core pull request #505
Opened 2021-12-10 11:22 UTC by 134dd3v

Many of the current v3 core libraries do not work with solc 0.8 in their present state, bc of their dependency on FullMath, TickBitmap or TickMath which contain some code that gives compilation error on solc 0.8.

Though after the changes in this PR the `FullMath.spec.ts`, `TickBitmap.spec.ts` and `TickMath.spec.ts` tests pass. But the gas tests fail. Also it changes the UniswapV3Pool bytecode. Hence, the PR does not intend to be merged on main branch.

FWIW, it would be great if Uniswap can publish an official `@uniswap/v3-core-0.8-support` kind of package, so that projects can conveniently build on Uniswap V3 using solc 0.8, without copy-pasting files to their repo and modifying code (which could potentially violate licences).

2021-12-30 05:22 UTC, misamoo approved these changes

2021-12-30 05:22 UTC, misamoo approved these changes

2021-12-30 05:44 UTC, misamoo approved these changes
d

2021-12-30 05:44 UTC, misamoo approved these changes
f

2021-12-30 05:44 UTC, misamoo commented
d

2021-12-30 05:45 UTC, misamoo approved these changes
d

2021-12-30 06:21 UTC, misamoo approved these changes
d

2021-12-30 06:25 UTC, misamoo approved these changes
f

2021-12-30 06:26 UTC, misamoo requested changes
d

2022-01-02 19:04 UTC, 134dd3v commented
Update: Seems that it's not feasible to support 0.7.6 and 0.8 with the same solidity source code, mainly due to the added checks in arithmetic. Code that'd work for 0.8 would involve `unchecked {}` blocks all over the place.

2022-01-07 02:19 UTC, fallingicarus approved these changes

2022-01-08 09:31 UTC, 7779043 approved these changes

2022-01-08 09:32 UTC, 7779043 approved these changes

2022-01-26 20:49 UTC, NoahZinsmeister commented
unfortunately, we're not going to commit changes for 0.8.x support that change the bytecode, as the system is already deployed. however, we've limited the pragma in a few libraries that rely on overflow to make the lack of support more explicit: https://github.com/Uniswap/v3-core/pull/525

2022-01-26 20:49 UTC, closed without merging

2022-01-26 21:07 UTC, moodysalem commented
one thing to consider is having additional libraries under `libraries/0_8_x` that are as well tested as the other core libraries

2022-02-04 01:48 UTC, jjranalli commented
Given the issue with `TickMath.sol`, what is the suggested way to derive price from a tick on `solc >0.8`?